apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devflow-ingress
  namespace: devflow-labs
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - devflowlabs.io
        - "*.devflowlabs.io"
      secretName: devflow-tls
  rules:
    - host: devflowlabs.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: config-service
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
    - host: "*.devflowlabs.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-interceptor
                port:
                  number: 8080
